### ISSUE TITLE
It doesn't seem to work...

### ISSUE THREAD

**Issue by grenzionky** [TSedlar/anitrack#26]
It doesn't update my kitsu after watching episodes even though the gui says I'm logged in. I tried it with masterani and netflix and it didn't work for either...

**Comment by TSedlar** [comment]
I've used both and it works for what I've watched unless they number it differently (i.e Season 2 Episode 1, rather than e.g Episode 13)

The title and episode fetching works on MasterAni and I've used it, which tracks correctly for me.

Maybe it's just an odd title? Let me know the URL to the video you're trying to track.

![](https://i.imgur.com/x4QpUvR.png)

Netflix however seems to be buggy since the video elements are in an off-site form, which I can fix via:

`(x.text ? x.text() : x.textContent).trim()`

I will push this fix live to 1.67 later today.
