### ISSUE TITLE
not working with animepahe

### ISSUE THREAD

**Issue by 0ANIMEFREAK0** [TSedlar/anitrack#32]
I think it isnt working with animepahe or i might be wrong dont know how to use it
i was watching this anime
https://animepahe.com/play/as-miss-beelzebub-likes/9ebb52e6c70cf6525ac21917b17ab1aaecab66bc
i waited for more than 15 min it didnt update my list as u can see
https://vgy.me/GwyUQh.png
idk if i messed up the login or something
https://vgy.me/nTa5No.png
and i am using vivaldi browser 
https://vivaldi.com

**Comment by TSedlar** [comment]
Works just fine for me:

![image](https://user-images.githubusercontent.com/924309/48676972-8b6b8280-eb2b-11e8-9172-ac2a3e2abcb6.png)

And has updated on my Kitsu:

![image](https://user-images.githubusercontent.com/924309/48676985-a807ba80-eb2b-11e8-8881-fa338f0136d3.png)

You can possibly see what's going on if you press Control+Shift+J and wait until the timer reaches over 300000 millis (5 minutes), and see if an error occurs.

I would assume it's simply because I don't have vivaldi supported and they may have a difference in the API.

The browsers that are strictly tested and supported are: Firefox, Chrome, and Opera.

I will leave this issue open for a few days to see if you're willing to leave me a screenshot of the browser console (Ctrl+Shift+J) after 5 minutes has elapsed while having that video 6 open; otherwise, I'll close this issue as non-supported browser.

**Comment by 0ANIMEFREAK0** [comment]
vivaldi was build using chromium

**Comment by TSedlar** [comment]
That doesn't mean that it uses the same API. It could be dated and not constantly merge in the same code whenever it is updated, etc. 

Just telling me that something doesn't work doesn't mean much when it works for me on the 3 browsers that I listed that I support.

I will need you to check the browser console after 5 minutes of being on the video 6 page that you linked, if you cannot do that I cannot get an error message and I will only be able to assume the error lies with a browser I do not support.

**Comment by 0ANIMEFREAK0** [comment]
I am trying to do that but its saying the console was cleared

**Comment by TSedlar** [comment]
There is two different consoles. 

The one you opened, at least in firefox, is opened via F12 or Ctrl+Shift+K. In firefox, that is called the Web Console. I need the browser console opened, which is through Ctrl+Shift+J.

The one you have opened does not have any debug information about the plugins/extensions you have, but rather just a debug console for the website scripts running on the currently opened tab.

**Comment by 0ANIMEFREAK0** [comment]
the one i opened was on vivaldi there was no console registered with this keys cntrl+shift+j  in  vivaldi

**Comment by 0ANIMEFREAK0** [comment]
found it 
https://vgy.me/kFlvtu.png

**Comment by 0ANIMEFREAK0** [comment]
i think i have to enable something that i didnt beacause i tried it on it shows the same error

**Comment by TSedlar** [comment]
This is because your username on Kitsu is "ANIMEFREAK", it needs to match your username.

https://kitsu.io/users/ZEREF1274

ANIMEFREAK is what their API would need to use to lookup your profile, but it won't let you log in with that name.

The solution is to make your profile name "ZEREF1274"

[This issue](https://github.com/TSedlar/anitrack/issues/29) happened for them as well, and that solution fixed it.

**Comment by yuslaw865** [comment]
hey, i recently installed some extensions and animepahe images stopped loading what can i do to get them to load without uninstalling the extensions. the extensions are popup blocker (strict), adguard adblocker, adblocker stand and avast security
