### ISSUE TITLE
Emby Support

### ISSUE THREAD

**Issue by brassica77** [TSedlar/anitrack#35]
Hi,
Can you add support for Emby?
Also, does the extension work in Firefox Mobile on Android?

**Comment by TSedlar** [comment]
If there is a web viewer for it, it is possible. I would need the source of the page to be able to tell if it's possible, as multiple things need to be parsed from the page:

- title
- episode


but I'm also unsure if chrome lets you read the source of locally opened urls, since you cannot with chrome:// urls.

I don't see why it wouldn't work on the mobile version, but it is untested.

**Comment by brassica77** [comment]
Thanks for the fast reply!

You need to create an account on their [site](https://emby.media/) first.
Then you need to download the server and install it, then configure it.
You should be able then to access it in a browser using this url :  app.emby.media
Once you run an anime episode, you'll be able to get all the episode info from the page.

There are other similar projects, like [Scrobbly](https://github.com/leonekmi/scrobbly) and [MAL-Sync](https://github.com/lolamtisch/MALSync) and they support Emby and Plex solutions, but they don't support Kitsu and Firefox Mobile support is buggy.

**Comment by TSedlar** [comment]
It's not my top priority at the moment as I'm busy with other things.

The best way to get this added would be for you to watch an episode and list the exactly video url to me here.

i.e app.emby.media/someseries/somevideonumber

and also attach the page source here. (ctrl+u in firefox)

**Comment by brassica77** [comment]
I watched an episode and the url was [this](http://app.emby.media/#!/videoosd.html)
I attached the source page.
[emby.txt](https://github.com/TSedlar/anitrack/files/2965822/emby.txt)

**Comment by TSedlar** [comment]
Ah seems I need you to get the page source a little bit differently I believe..

Otherwise I don't believe I can support emby if the way I have you get it is similar to the output above.

Can you try right clicking anywhere on the page and inspecting the element?

Go to the top of the html tag and right click copy > outer html

![image](https://user-images.githubusercontent.com/924309/54389123-9e670d00-465c-11e9-8de2-549b7759fa83.png)

Because the page source you gave me has no indication of the video you're watching :/

**Comment by brassica77** [comment]
Like this?
I am using Chrome by the way.
[Emby.txt](https://github.com/TSedlar/anitrack/files/2968620/Emby.txt)

**Comment by TSedlar** [comment]
Yup! So it looks like I can add support in a bit for it.

Verify if I'm correct below please!

The anime you watched was: 
 - title: How clumsy you are, Miss Ueno
 - episode: 10? (i'm unsure about this one as it doesn't seem entirely obvious like the title is)

### self notes
This is for adding support when I get more of a chance later tomorrow or saturday:
- title selector: `div[class=detailSection] div[class=nameContainer] h1`
- episode selector: `div[class*='nextUpItems'] div div div button[class*='itemAction']`

- regex for episode selector: `- ([0-9]+)`

**Comment by brassica77** [comment]
Yes, this was the anime and the episode I was watching during the test.

**Comment by brassica77** [comment]
@TSedlar any luck?

**Comment by TSedlar** [comment]
I'm rather busy with school work and other IRL stuff at the moment but I will get to it in the near future.

```json
"emby": {
  "type": "anime",
  "urls": [
     "*://app.emby.media/#!/videoosd.html"
  ],
  "title": "div[class='detailSection'] div[class='nameContainer'] h1",
  "episode": {
    "pattern": "div[class*='nextUpItems'] div div div button[class*='itemAction']",
    "processor": "- ([0-9]+)",
    "groups": [1]
  }
}
```

The above should just be needed to be added to [sources.json](https://github.com/TSedlar/anitrack/blob/master/src/shared/sources.json) and have a version number bump + be built.

It needs to be tested, of course, it'll just take me a bit, but feel free if you're savvy enough with this stuff. Otherwise it'll have to wait a bit.

**Comment by brassica77** [comment]
No problem, I will wait : unfortunately, I am only a user and don't have the knowledge to build a release.

**Comment by TSedlar** [comment]
Just to update I'll be getting to this later tonight or mid-day tomorrow 👍

**Comment by TSedlar** [comment]
Building and releasing now. It should be live sometime later today after they review.

**Comment by brassica77** [comment]
Thanks!
I can't get to login to MAL, it keeps refusing with a login failed error in Mobile Firefox. I haven't tested on desktop browser yet.
Kitsu connection is fine, but I see nothing while watching a video : how can I be sure it is running and scrobbling, other than waiting for an episode to finish and check if it was updated?

**Comment by TSedlar** [comment]
MAL 3rd party API has been down for over a year, it has not worked since they have taken it down for anyone. You can track with Kitsu and export to MAL from Kitsu if you really want to use MAL. I have kept support in this plugin for when they fix their problems.

There isn't a notification during you watching because it would distract from watching the episode/reading manga.

It should update after 5 minutes of watching. You can view this in the Web Console. You also need to make sure that your username is the same as your login name, as Kitsu does not offer a lookup of your profile in the API via email/login name, only the profile name.

**Comment by brassica77** [comment]
Thanks for the explanations.

As far as I know, there are other extensions/apps that are using a workaround to still use MAL API, like Tachiyomi or MAL-Sync, something to do with the cookies from MAL in one's browser I think. Maybe you can check their codes (they are on Github) to see how they do if you want to add it.

I tried with Kitsu : it worked in Chrome on my Desktop, but failed in Firefox Mobile on my Android phone.
Also, I think the 5 minutes wait is not ideal : some shows I watch are 3 minutes long, some are 10 minutes long, some are full length movies, and sometimes when I start watching an episode, I might not finish it immediatly. Wouldn't a percentage be better, something like after 75% of an episode, it will update the status?

**Comment by TSedlar** [comment]
I'm not making a workaround for MAL when it is on their end to fix their own problems. It would require a rewrite of a lot of code that will eventually work when they get their stuff in order (if they ever do, it's a joke they haven't fixed it in over a year when they know it affects multiple 3rd party programs.)

Good to know it works on desktop.

Mobile is not a priority for me to debug, I don't see any reason why it shouldn't work on mobile when it works just fine on the desktop, unless the mobile firefox extension API is different.

There is not an easy way to get embedded video length of every single source that I have supported.

Sorry it does not work for your needs, this is an issue not regarding to supporting Emby, as you have stated it works on the desktop and support has been added.
